### ISSUE TITLE
colorscheme isn't actually changing colors. I plugged the repo and set colorscheme shado, but all the colors remain the exact same as if I didn't.

### ISSUE THREAD

**Issue by tau-q** [Shadorain/shadotheme#10]
I don't receive any error that "colorscheme shado doesn't exist", or whatever the exact wording is.

**Comment by tau-q** [comment]
Just incase it matters, I also tried the legacy branch and installing it manually, same thing.

**Comment by Shadorain** [comment]
Hey @kayte-q I'm super sorry about this! Looking into this now. Had a recent move to lua as well so that may help clear things up. Oddly enough too i found that if you dont load shadotheme after treesitter gets loaded too it may get funky. Not sure if that is the same issue you are having. Will try to figure this out soon.
Thanks for trying the theme though!

**Comment by Shadorain** [comment]
I was able to fix some stuff up with the Lua port tonight. Try seeing with it if anything is fixed or not. I'd assume not being you've tried old versions as well but worth a shot. Will look more at this issue tomorrow.

Thanks for bringing it up!!

**Comment by tau-q** [comment]
Hi @Shadorain I ran :PlugUpdate and reloaded nvim, but instead I got this message:

Error detected while processing /home/amber/.local/share/nvim/plugged/shadotheme/colors/shado.lua:
E5113: Error while calling lua chunk: ...er/.local/share/nvim/plugged/shadotheme/colors/shado.lua:129: attempt to index field 'cmd' (a function value)
stack traceback:
        ...er/.local/share/nvim/plugged/shadotheme/colors/shado.lua:129: in main chunk
Press ENTER or type command to continue

Thank you for helping btw

**Comment by Shadorain** [comment]
Sure no need to thank me! 😁 

Awesome thank you for testing too. Try the newest commit, I changed it to just run vimscript from lua for the highlight clear command where your's is getting tripped up. Make sure to be running latest nvim version as well!

**Comment by tau-q** [comment]
I updated again and now it's saying "error detected while processing /home/usr/.local/share/nvim/plugged/shadotheme/colors/shado.lua:", then "W18: Invalid character in group name" repeated a bunch of times over. Loading it anyways makes syntax all completely white.

**Comment by Shadorain** [comment]
Hm definitely an issue with the version you are running. It isnt supporting the new treesitter highlighting style with `@` syntax. Try to build nvim from source and then post the running version here?

**Comment by tau-q** [comment]
I compiled nvim from github and ran that, this time it gave no errors but it was still all white. The compiled version was 0.8.0, the apk version was 0.7.0

edit: just incase it wasn't gaurenteed, compiled nvim was using my init.vim file. I turned off the colorscheme and it went back to normal. I also ran a plugUpdate incase anything changed and same thing.

**Comment by Shadorain** [comment]
Thats super odd... maybe because it is init.vim it doesnt like certain things 🤔  I really am not sure what is going on. Do you have your updated conf online somewhere?

**Comment by tau-q** [comment]
I made a pastebin link for it: [https://pastebin.com/h1q4rZUC](https://pastebin.com/h1q4rZUC)

**Comment by tau-q** [comment]
update: I the commit before the lua port and got the issue this started with.

**Comment by Shadorain** [comment]
Ah gosh... I think you just are missing the `set termguicolors` piece. That should fix it all up. Please let me know! so sorry about the delay!

**Comment by tau-q** [comment]
It worked! Thank you for all the help, and sorry if I wasted your time.

**Comment by Shadorain** [comment]
Sure anytime! Glad that worked, no no sorry I didn't think about mentioning that earlier 🤣  No no never a waste. Glad we got that figured out! Good work 😁
