### ISSUE TITLE
Kitty theme

### ISSUE THREAD

**Issue by kelpwave** [Shadorain/shadotheme#12]
![image](https://user-images.githubusercontent.com/108518033/223725974-6f7ec210-d812-4585-9ce1-8f1a13da0a8d.png)
 

Wrote a theme for Kitty.

[It just got merged into Kitty Themes as I was writing this.](https://github.com/kovidgoyal/kitty-themes)

[Here's  theme.config file](https://github.com/kovidgoyal/kitty-themes/blob/master/themes/shadotheme.conf)
Please let me know if you want any changes :)

**Comment by Shadorain** [comment]
Wow this is great! Thank you for making this for shadotheme!
It looks great, I'll definitely let you know if I'd want any changes but it seems quite perfect as it is right now. You're awesome, I appreciate it a lot.
