### ISSUE TITLE
Makes everything gray

### ISSUE THREAD

**Issue by J-Kistner** [Shadorain/shadotheme#13]
Tried using it and activating it in both an init.vim and through nvim commands but it just makes everything gray

**Comment by J-Kistner** [comment]
shado-legacy works while the non-legacy version doesn't

**Comment by Shadorain** [comment]
Hi, thanks for reporting this. That is odd, I'm not experiencing any issues. Let me do some tests...

Could you show me how you are invoking shadotheme? Also what language you are testing it on

**Comment by Shadorain** [comment]
I have this in Lazy to load shadotheme and I use `nvim-transparent` as well to have the nice transparency:
```lua
  {
    "Shadorain/shadotheme",
    lazy = false,
    config = function()
      vim.cmd.colorscheme("shado")
      vim.cmd([[hi Keyword gui=italic]])
    end,
  },

  {
    "xiyaowong/nvim-transparent",
    event = "VimEnter",
    config = true,
  },
```

**Comment by J-Kistner** [comment]
Been a minute but I'm using packer and accessing nvim through ssh on windows ( which could very well be the issue ). Is there something special to install it with packer?

**Comment by Shadorain** [comment]
No problem man! That's odd could you send a screenshot for me? that might help me debug it a little for you!
There really shouldnt be, I used to use packer too with this but maybe somethings changed

**Comment by J-Kistner** [comment]
No clue why--but it's working now. I did switch the os I was running the server on. Very possible the ubuntu server I was running just couldn't do the colors. Weird that it worked with other colorschemes though.
