### ISSUE TITLE
Shadotheme for airline

### ISSUE THREAD

**Issue by TarunDaCoder** [Shadorain/shadotheme#5]
Hey shado,
Is there some kind of theme like this for airline too, cuz I use airline, it looks pretty good, if you can, can you create shadotheme for airline too?
Thanks

**Comment by Jonathan-1407** [comment]
<img src="https://i.ibb.co/C6nThh1/Screenshot-20210508-142229.png" alt="theme zenburn airline" title="Zenburn">

In your `.vimrc` file put the following line
`let g:airline_theme = "zenburn"` This theme comes by default in the airline you do not have to install it
@TarunDaCoder This theme I use

**Comment by TarunDaCoder** [comment]
ok, thanks @Jonathan-1407
