### ISSUE TITLE
it adds a cursorline and does not have better comment syntax

### ISSUE THREAD

**Issue by ronyAhmed1200** [Shadorain/shadotheme#8]
After installing it, I am seeing `cursorline` with this theme in my termianal which is distracting.. And another thing is that it doesn't make `better comment syntax`. I mean, I would like to see my comment little bit off comparing to my code. 

So i uninstalled the theme. If these issues are fixed, then i would like to try it again...

**Comment by dvchoudh** [comment]
The comments syntax highlighting are very much different, than the other color values. I don't see how you can't, differentiate from them.

**Comment by Shadorain** [comment]
> After installing it, I am seeing `cursorline` with this theme in my termianal which is distracting.. And another thing is that it doesn't make `better comment syntax`. I mean, I would like to see my comment little bit off comparing to my code.
> 
> So i uninstalled the theme. If these issues are fixed, then i would like to try it again...

Ah thank you for your concerns! Im not sure what you mean about the cursorline piece honestly, could you post a screenshot? 
And to the comment syntax, I am assuming you are talking about in nvim, and the color of your comments. I believe the color I picked for comments actually sticks out very well where it makes it easier to read the code without being distracted by the comments but also easily be able to see where they are. If you have something different on yours than in my screenshots posted on the Readme, please show me! Thanks

**Comment by ronyAhmed1200** [comment]
Look, there is a cursor line in nvim.. and the comment lines color are as same as the code. Which is distracting really... 

![image](https://user-images.githubusercontent.com/75775786/125191286-6a6b7900-e263-11eb-95ee-d7ea02bb3f2c.png)

**Comment by dvchoudh** [comment]
> Look, there is a cursor line in nvim.. and the comment lines color are as same as the code. Which is distracting really...
> 
> ![image](https://user-images.githubusercontent.com/75775786/125191286-6a6b7900-e263-11eb-95ee-d7ea02bb3f2c.png)

The colorscheme you're using in the screenshot provided is not shadotheme. I would recommend applying shadotheme theme in your config file, and checking again. And just for your information, you can set it by doing `colorscheme xshado`

**Comment by Shadorain** [comment]
First off, if they do happen to be the same color then just simply change the highlight value lol, It is very easy, just edit the xshado.vim file in colors/ and change the CursorLine values to what u want. If that is what it takes to make u not use a colorscheme that is odd lol. 
Plus what binx said, that is not my theme at all.

**Comment by ronyAhmed1200** [comment]
I ensurend there is colorscheme xshado appied.. and i would like to get rid of cursorline and the comment should be a little light / something different color from the code... bcz it is hard to identify between them..  
and pls tell me the commands / code to achive this..

**Comment by dvchoudh** [comment]
Have you actually installed the theme ?
